name: Environment Variable Test

on: [push]

env:
  env_var: ${{ vars.TEST }}
  env_var1: ${{ vars.TEST1 }}
  
jobs:
  print_variables:
    runs-on: ubuntu-latest
    environment: Actions
    steps:      
      - name: Print global variable
        run: |
          echo "Global Variable is $vars.TEST"
          echo "Job Specific Variable1 is ${{ vars.TEST }}"
          echo "Job Specific Variable1 is ${{ env.TEST }}"
          echo "Job Specific Variable1 is $env_var"
          echo "Job Specific Variable1 is $env.TEST"
          
      - name: Print job specific variable
        run: |
          echo "Job Specific Variable1 is $env.TEST1"
          echo "Job Specific Variable1 is ${{ vars.TEST1 }}"
          echo "Job Specific Variable1 is $env_var1"
          
      - name: Print job secret
        run: echo "Job Specific Variable is ${{ secrets.TOKEN }}"
        
      - name: Set and print step specific variable
        run: |
          STEP_VAR="Step Specific Value"
          echo "Step Specific Variable is $STEP_VAR"
